### ISSUE TITLE
error in log file

### ISSUE THREAD

**Issue by nabil215** [sunnynevarekar/Road-Segmentation#1]
OSError: [Errno 22] Invalid argument: 'C:\\Users\\dell\\Downloads\\Compressed\\Road-Segmentation\\logs\\train_run_07-02-2021_21:34:24.log'

**Comment by sunnynevarekar** [comment]
The issue is w.r.t log filenames that are generated for each training run. The filename format is not valid on windows. Delete the log files from logs folder and in `src /logger.py` change `strft` to valid filename on windows.
 ```
#timestamp for file
 strft = datetime.now().strftime('%d-%m-%Y_%H:%M:%S') 
```

to something like

```
#timestamp for file
 strft = datetime.now().strftime('%d-%m-%Y_%H-%M-%S') 
```
